In [1]:
import sys
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

pd.set_option('display.mpl_style', 'default')

/home/tim/miniconda3/envs/project/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2862: FutureWarning:
mpl_style had been deprecated and will be removed in a future version.
Use `matplotlib.pyplot.style.use` instead.

  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
first_df = pd.read_csv('all-7-5.csv',low_memory=False)

In [3]:
first_df

        index speed  caculate_x   caculate_y  caculate_z
0           1  81.9  219.399586   139.192676  222.127078
1           1  81.9  218.587436   166.504547  220.988721
2           1  81.9  217.767626   193.807500  219.817501
3           1  81.9  216.940145   221.101500  218.613213
4           1  81.9  216.104979   248.386509  217.375906
5           1  81.9  215.262115   275.662494  216.105538
6           1  81.9  214.411540   302.929416  214.801887
7           1  81.9  213.553242   330.187242  213.464895
8           1  81.9  212.687207   357.435934  212.094505
9           1  81.9  211.813423   384.675457  210.690660
10          1  81.9  210.931877   411.905776  209.253302
11          1  81.9  210.042556   439.126854  207.782375
12          1  81.9  209.145448   466.338657  206.277821
13          1  81.9  208.240538   493.541149  204.739584
14          1  81.9  207.327816   520.734294  203.167606
15          1  81.9  206.407267   547.918056  201.561831
16          1  81.9  205.478879   575.092401  199.922295
17          1  81.9  204.542640   602.257294  198.249061
18          1  81.9  203.598536   629.412698  196.541905
19          1  81.9  202.646555   656.558578  194.801064
20          1  81.9  201.686685   683.694901  193.026282
21          1  81.9  200.718912   710.821629  191.217773
22          1  81.9  199.743224   737.938729  189.375291
23          1  81.9  198.759608   765.046166  187.499027
24          1  81.9  197.768051   792.143904  185.588819
25          1  81.9  196.768542   819.231908  183.644622
26          1  81.9  195.761066   846.310144  181.666540
27          1  81.9  194.745613   873.378577  179.654441
28          1  81.9  193.722168   900.437172  177.608269
29          1  81.9  192.690720   927.485895  175.527996
...       ...   ...         ...          ...         ...
222903   3585  60.0  191.873709  1400.259618   56.364854
222904   3585  60.0  191.752649  1417.581273   58.949082
222905   3585  60.0  191.631457  1434.893318   61.465131
222906   3585  60.0  191.510132  1452.195743   63.912797
222907   3585  60.0  191.388676  1469.488538   66.291874
222908   3585  60.0  191.267087  1486.771696   68.602156
222909   3585  60.0  191.145366  1504.045206   70.843438
222910   3585  60.0  191.023513  1521.309060   73.015512
222911   3585  60.0  190.901528  1538.563248   75.118171
222912   3585  60.0  190.779412  1555.807761   77.151208
222913   3585  60.0  190.657164  1573.042591   79.114415
222914   3585  60.0  190.534785  1590.267728   81.007583
222915   3585  60.0  190.412274  1607.483163   82.830505
222916   3585  60.0  190.289631  1624.688888   84.582970
222917   3585  60.0  190.166858  1641.884893   86.264770
222918   3585  60.0  190.043953  1659.071170   87.875694
222919   3585  60.0  189.920917  1676.247709   89.415533
222920   3585  60.0  189.797750  1693.414502   90.884077
222921   3585  60.0  189.674452  1710.571540   92.281113
222922   3585  60.0  189.551024  1727.718815   93.606432
222923   3585  60.0  189.427465  1744.856317   94.859821
222924   3585  60.0  189.303775  1761.984038   96.041070
222925   3585  60.0  189.179954  1779.101969   97.149965
222926   3585  60.0  189.056003  1796.210102   98.186296
222927   3585  60.0  188.931922  1813.308428   99.149849
222928   3585  60.0  188.807711  1830.396937  100.040411
222929   3585  60.0  188.683369  1847.475623  100.857770
222930   3585  60.0  188.558897  1864.544476  101.601713
222931   3585  60.0  188.434296  1881.603487  102.272025
222932   3585  60.0  188.335448  1895.116974  102.756480

[222933 rows x 5 columns]

In [5]:
first_df.describe()

               index     caculate_x     caculate_y     caculate_z
count  222933.000000  222933.000000  222933.000000  222933.000000
mean     1838.075377     172.167854    1032.310976      98.158522
std      1086.186845      38.869096     500.860389      63.516419
min         1.000000      38.044359     127.288636       0.019300
25%       809.000000     148.029741     603.889336      44.818131
50%      1882.000000     182.161048    1044.386198      86.022637
75%      2853.000000     200.762911    1458.175340     151.357315
max      3585.000000     292.527421    1895.144770     353.763534

In [6]:
def split_train_test(data, test_ratio):
    shuffled_indices = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled_indices[:test_set_size]
    train_indices = shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [ ]:

#train_set, test_set = train_test_split(housing, test_size=0.2, random_state=42)

In [11]:
housing = first_df.copy()
corr_matrix = housing.corr()
corr_matrix["caculate_x"].sort_values(ascending=False)

caculate_x    1.000000
caculate_z    0.044673
index         0.040019
caculate_y   -0.174352
Name: caculate_x, dtype: float64

In [1]:
encoder = LabelEncoder()
housing_cat = housing["speed"]
housing_cat_encoded = encoder.fit_transform(housing_cat)
housing_cat_encoded

NameError: name 'LabelEncoder' is not defined